version: '1'
services:
  symfony:
    build: .
    restart: always
    ports:
      - "8080:8000"
    links:
      - docupet-db
  docupet-db:
    build: ./docker/mysql/
    restart: no
    environment:
      MYSQL_DATABASE: docupet
      MYSQL_USER: docupet
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
